#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;
use App\Console\ServeInterceptor;

define('XENOPHP_START', microtime(true));

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap XenoPHP and handle the command...
/** @var Application $app */
$app = require_once __DIR__ . '/bootstrap/app.php';

// Handle custom loop logic for "php xeno serve"
ServeInterceptor::intercept();

$status = $app->handleCommand(new ArgvInput);

exit($status);
